version: '3.8'

services:
  app:
    image: yiisoftware/yii2-php:8.2-fpm
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: loan_app_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5433:5432"

networks:
  app-network:
    driver: bridge
